### ISSUE TITLE
Personenverzeichnis/ Glossar

### ISSUE THREAD

**Issue by CanaKussmaul** [CanaKussmaul/Vietnam#18]
@AlicjaPolakiewicz was denkst du?

**Comment by AlicjaPolakiewicz** [comment]
Oopsie, sorry. Ja grundsätzlich immer eine gute Idee. ich bin auch für einen Zeitstrahl. Oder sogar zwei die miteinander in Bezieung stehen, also einen für KK und einen für VK

**Comment by CanaKussmaul** [comment]
Uh. das wär schon cool. Ich mach ein neues Issue auf, ja? Und hier mach ich eine oder zwei Listen auf würd ich sagen. Müssen wir halt einfach gucken, wie und ob wir das schaffen
