### ISSUE TITLE
Quellenverzeichnis

### ISSUE THREAD

**Issue by CanaKussmaul** [CanaKussmaul/Vietnam#21]
Kurzkommentare Nutzung
Einordnung bzw. Bewertung fünf wichtigste Quellen (Fließtext)

**Comment by CanaKussmaul** [comment]
Vorgeschichte
http://geschichtsverein-koengen.de/KalterKrieg.htm
http://de.wikipedia.org/wiki/Vietnam_unter_franz%C3%B6sischer_Kolonialherrschaft
http://www.ag-friedensforschung.de/regionen/Vietnam/chronik.html
http://www.lsg.musin.de/geschichte/geschichte/lkg/Verfassungen/imperialismus-F.html
http://www.britannica.com/EBchecked/topic/628349/Vietnam/52736/The-conquest-of-Vietnam-by-France
http://alphahistory.com/vietnam/french-colonialism-in-vietnam/
http://www.history.com/this-day-in-history/vietnam-independence-proclaimed
http://www.vietquoc.com/0007vq.htm
Indochinakrieg
http://universal_lexikon.deacademic.com/253341/Indochinakrieg
http://www.oliver-bieri.ch/kalter-krieg/kk/indochina.htm
http://www.coldwar.org/articles/40s/FirstIndochinaWar.asp
http://www.britannica.com/EBchecked/topic/286443/Indochina-wars

USA in Vietnam
http://www.bpb.de/apuz/31129/die-usa-und-vietnam?p=all
http://www.uni-protokolle.de/Lexikon/Vietnamkrieg.html
http://www.aref.de/kalenderblatt/2009/32_vietnamkrieg_eintritt_usa_1964.php
http://mcadams.posc.mu.edu/goldzwig.htm
https://www.maryferrell.org/wiki/index.php/Walkthrough_-_Vietnam_in_Late_1963
http://www.welt.de/kultur/history/article106402595/Der-Praesident-dem-der-Kennedy-Mord-zugetraut-wird.html
http://presidentialrecordings.rotunda.upress.virginia.edu/essays?series=Vietnam
http://www.lbjlibrary.org/exhibits/the-vietnam-conflict
http://www.digitalhistory.uh.edu/disp_textbook.cfm?smtID=2&psid=3464
http://www.bbc.co.uk/news/magazine-21768668
http://www.spiegel.de/einestages/tonkin-zwischenfall-1964-usa-im-vietnamkrieg-a-983990.html
http://www.uni-protokolle.de/Lexikon/Vietnamkrieg.html
http://www.freidok.uni-freiburg.de/volltexte/534/pdf/Dominotheorie.pdf
http://www.uni-protokolle.de/Lexikon/Domino-Theorie.html
http://www.english.illinois.edu/maps/vietnam/causes.htm
http://thevietnamwar.info/why-did-the-vietnam-war-start/
http://www.stresemann-gesellschaft.de/downloads/Stresemann-Vortrag-2009.pdf
http://www.diss.fu-berlin.de/diss/servlets/MCRFileNodeServlet/FUDISS_derivate_000000001368/03_mpi4.pdf?hosts=
http://www.foreignaffairs.com/articles/49060/stephen-e-ambrose/trapped-by-success-the-eisenhower-administration-and-vietnam-195



Zusatz
http://watergate.info/
http://www.britannica.com/EBchecked/topic/631640/Vo-Nguyen-Giap
http://www.washingtonpost.com/local/obituaries/military-leader-vo-nguyen-giap-defeated-french-us-forces-in-vietnam-conflicts/2013/10/04/897ffff2-c5da-11df-94e1-c5afa35a9e59_story.html
http://www.whoswho.de/bio/ho-chi-minh.html
http://www.bbc.co.uk/history/historic_figures/ho_chi_minh.shtml
http://de.wikipedia.org/wiki/Chinesisch-Franz%C3%B6sischer_Krieg
http://www.lsg.musin.de/geschichte/geschichte/lkg/Int-pol/china.htm
http://althistory.wikia.com/wiki/Treaty_of_Hue_%28Napoleon%27s_World%29
http://www.britannica.com/EBchecked/topic/628312/Viet-Minh
http://www.welt.de/kultur/literarischewelt/article135924973/Als-die-Bolschewisten-wueteten-wie-heute-der-IS.html
http://www.zeit.de/wissen/geschichte/2011-10/kaiserreich-china

**Comment by CanaKussmaul** [comment]
Steininger, Rolf, Der Vietnamkrieg, Frankfurt am Main, 2004
Frey, Marc, Geschichte des Vietnamkriegs. Die Tragödie in Asien und das Ende des amerikanischen Traums, Münchem, 1998
McNamara, Robert S. with Brian VanDeMark, In Retrospect. The Tragedy and Lessons of Vietnam, 1995, New York
Gaddis, John Lewis, Der Kalte Krieg. Eine neue Geschichte, 2007, München

Bundeszentrale für politische Bildung (Hrsg.), Informationen zur politischen Bildung 254, Internationale Beziehungen 1. Der Ost-West-Konflikt, 2003, Bonn

**Comment by AlicjaPolakiewicz** [comment]
Vorgeschichte 
http://www.bpb.de/izpb/10044/kriegsziele-der-alliierten?p=all
http://de.wikipedia.org/wiki/Teheran-Konferenz
http://de.wikipedia.org/wiki/European_Advisory_Commission
http://www.ibiblio.org/pha/policy/1943/431000a.html
http://www.buehler-hd.de/gnet/neuzeit/zwanz/wk2/konferenzen.pdf
https://books.google.de/books?id=xlRjy4qnH6cC&pg=PT375&lpg=PT375&dq=stalin+the+bounds+of+what+is+tolerable&source=bl&ots=Cw-LNOR5rl&sig=06xFTugp_92waUbX-invt4htHjQ&hl=en&sa=X&ei=xD6YVI3yB4P-UuqfhLAL&ved=0CCMQ6AEwAA#v=onepage&q=stalin%20the%20bounds%20of%20what%20is%20tolerable&f=false
koengen.de/KalterKrieg.htm
http://ciml.250x.com/archive/stalin/german/stalin_ueber_den_grossen_vaterlaendischen_krieg.pdf

Sowjetunion nach 2 WK
http://www.bpb.de/internationales/europa/russland/47918/revolutionaere-neuordnung-und-stalin-diktatur-1918-1953?p=all
marxismus-leninismus.html
http://jugendbibliothek-gera.7to.de/files/download/ml-reader.pdf
http://universal_lexikon.deacademic.com/270671/Marxismus-Leninismus%3A_%C3%9Cber_den_dialektischen_und_historischen_Materialismus
http://de.wikipedia.org/wiki/Stalinismus
http://de.wikipedia.org/wiki/Marxismus-Leninismus

Bedeutung Vietnam
http://www.damals.de/de/16/Die-Sache-mit-Chruschtschows-Schuh.html?issue=167656&aid=167637&cp=1&action=showDetails
http://www.vietnamkrieg.de/vp.html
http://www.bpb.de/izpb/10339/vom-kalten-krieg-zur-aera-der-entspannung?p=all
http://de.wikipedia.org/wiki/14-Punkte-Programm
http://www.cvce.eu/content/publication/1997/10/13/914edbc9-abdf-48a6-9c4a-02f3d6627a24/publishable_de.pdf
http://popp-sport.de/02%20Geschichtsunterricht/12%20Pruefung/08%201945-1949/PDF%20Etappen%20Spaltung/s10%201947%2009%202Lagertheorie.pdf
https://www.abiweb.de/geschichte-neuordnung-der-welt-nach-1945/der-kalte-krieg/grundtheorien-des-kalten-krieges/zwei-lager-theorie.html
https://www.marxists.org/deutsch/archiv/lenin/1920/06/natfrag.htm
http://avalon.law.yale.edu/20th_century/wilson14.asp

Außenpolitik Chruschtschow
http://www.uni-protokolle.de/Lexikon/Chinesisch-sowjetisches_Zerw%FCrfnis.html
http://de.wikipedia.org/wiki/Gro%C3%9Fer_Sprung_nach_vorn
http://www.vietnam-kompakt.de/der-vietnamkrieg-teil-2.html
http://www.1000dokumente.de/index.html?c=dokument_ru&dokument=0014_ent&object=pdf&st=&l=de
http://www.spiegel.de/spiegel/print/d-43066862.html
http://www.zeit.de/index
http://www.spiegel.de/spiegel/print/d-46273576.html
http://www.infopartisan.net/archive/maowerke/polemik.htm
http://www.neue-einheit.com/deutsch/atomwaffensperrvertrag/atomfetischismus.htm

Außenpolitik Breschnew
http://www.uni-protokolle.de/Lexikon/Breschnew-Doktrin.html
http://www.spiegel.de/spiegel/print/d-45702152.html

Andere
John Gaddis, Der Kalte Krieg eine neue Geschichte
Carole K. Fink, Cold War, An international history
Marc Frey, Geschichte des Vietnamkriegs
BPB Internationale Beziehungen I

**Comment by CanaKussmaul** [comment]
@AlicjaPolakiewicz du musst bei deinen anderen noch die Jahreszahlen und so angeben, also bei John, Mark und BPB nicht, die hab ich schon gemacht, aber bei Carole. Und bei den Internetadressen müssen wir beide noch zuletzt angesehen am machen
