### ISSUE TITLE
Darstellung des Arbeitsprozesses

### ISSUE THREAD

**Issue by AlicjaPolakiewicz** [CanaKussmaul/Vietnam#24]
Darstellung und Begründung der Themenfindung, Themenwahl
Einordnung Thema fachwissenschaftlicher Zusammenhang
Begründung mögliche Medien- und Methodenwahl

**Comment by AlicjaPolakiewicz** [comment]
@CanaKussmaul 
Haben wir uns jetzt schon überlegt, was für Medien und Methoden wir einsetzen möchten und warum?

Zu den Medien habe ich jetzt erstmal vorläufig:

PowerPoint: schon beim MSA, unterstützdende Wirkung, verleiht Struktur, zentrale Punkte können hervorgehoben werden, Anschauungsmaterial kann verwendet werden; aber: minimalistischer Einsatz

Plakate: (1) Gliederung: beständig, verschwindet nicht beim Umblättern auf nächste Folie, dient der Orientierung für Zuhörer, Struktur
(2) Karte: Darstellen Truppenbewegungen, Unterteilung in Nord- und Südvietnam von zentraler Bedeutung bei vielen Unterthemen -> Verhindern Redundanz durch ansonsten häufig benötigten Einsatz einer Folie mit Karte in der Präsentation

Aber Methoden-wise? Kein Streitgespräch, ich weiß. Aber was sonst? Wir brauchen schon noch ein special. 

Hast du sonst noch was an Medien, die du gerne einsetzen möchtest, oder fehlen dir noch Begründungen?

**Comment by CanaKussmaul** [comment]
Ne. Alles schick mit den Medien. Methoden ist halt ein Piss. keine ahnung was, aber wir müssen uns da echt was überlegen..

**Comment by AlicjaPolakiewicz** [comment]
okay, das können wir ja dann noch mal morgen oder so besprechen. Ich lass das mal erst mal noch raus und dann ergänze ich das gegebenenfalls.

**Comment by CanaKussmaul** [comment]
Oke.

**Comment by AlicjaPolakiewicz** [comment]
warte, mir fällt gerade auf: vielleicht müssen wir das mit der karte als plakat auch noch mal überlegen. Kann man das nicht doch besser auf einer Folie zeigen. Ich meine, ich werde es ziemlich sicher nicht brauchen, ich weiß nicht wie es bei dir aussieht und ich will nicht mit sowas wie:

"Mit der Landkarte in Form eines Plakates verhält es sich ähnlich. Die Unterteilung des Vietnams in Nord- und Südvietnam zur Zeit des Kriegs ist bei vielen Unterthemen von zentraler Bedeutung und zieht sich durch den gesamten Vortrag. "

unser Todesurteil unterschreiben...

**Comment by CanaKussmaul** [comment]
hmm. Man das ist arsch. Lass uns medien und methoden nochmal am freitag besprechen, wenn wir (hoffentlich) mit dem ganzen inhaltlichen durch sind

**Comment by AlicjaPolakiewicz** [comment]
erst freitag? lass uns das mal wirklich vorher schon abklären, ich meine, das kann man ja mehr oder weniger abschätzen. So ich hab jetzt eine vorläufige Version der "Darstellung des Arbeitsprozesses". Noch nicht komplett ausgearbeitet, aber ich hab ja noch ein bisschen Zeit, was das angeht und außerdem werden wir das am freitag ja auch noch tun.

**Comment by CanaKussmaul** [comment]
Ja die Frage ist wann

**Comment by AlicjaPolakiewicz** [comment]
funny, ich weiß, miss. Ich hol dich morgen nicht ab, ja? 
Ich weiß nicht, ich würde schon sagen, so morgen oder dienstag. dann können wir ja einfach ein extended call machen. oder ein meet-up. Ich meine, wenn wir konzentriert dran bleiben, sollte das auch nicht allzu lange dauern

**Comment by CanaKussmaul** [comment]
Ich weiß. 
Okeh, können wir ja dann morgen kurz klären
